### ISSUE TITLE
Application need to be run on all environment

### ISSUE THREAD

**Issue by anuragteapot** [NJACKWinterOfCode/iitpConnect#1]
Currently, application working good with Xampp server on Linux.
Task: Need to be all work in each type of environment and each type of OS (Operating System).

**Comment by rkishan516** [comment]
I am working on This. Can I ?

**Comment by Anu1601CS** [comment]
#9

**Comment by anuragteapot** [comment]
#9

**Comment by anuragteapot** [comment]
#9
